update contacts
SAV15/ice-cream-LazyIT pull request #24
Opened 2022-09-19 18:17 UTC by KlimovAnton

update

2022-09-19 19:20 UTC, SAV15 requested changes
Поправь то, что я сказал по стрелочке и можно пушить в мейн)

2022-09-19 19:20 UTC, SAV15 commented on src/images/svg/symbol-defs.svg
> +<symbol id="button-arrow" width="11" height="11" viewBox="0 0 7 10">
Будет херня. Размеры не соответствуют вьюбоксу. Чтобы выровнялось по центру по высоте используй text-align

2022-09-19 19:29 UTC, KlimovAnton commented on src/images/svg/symbol-defs.svg
> +<symbol id="button-arrow" width="11" height="11" viewBox="0 0 7 10">
сделал

2022-09-20 19:14 UTC, SAV15 approved these changes, later dismissed

2022-09-20 19:15 UTC, SAV15 approved these changes

2022-09-20 19:15 UTC, merged